version: '3.4'

services:
  db:
    image: ${DOCKER_REGISTRY-}mysql
    volumes:
        - datafiles:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 1234
  potentialcrud:
    image: ${DOCKER_REGISTRY-}potentialcrud
    build:
      context: .
      dockerfile: PotentialCrud/Dockerfile
    depends_on:
        - db
    ports: 
        - "49165:80"
    restart: always
    environment:
        - DBHOST=db
        - ASPNETCORE_ENVIRONMENT=Development
